"""
Django settings for web_scrapping_concursos project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-153_nc*a(ncv2r7znzvj3heb7rv#bxhi=x=g-=3-k)mg(-2hot'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'concursos'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_scrapping_concursos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_scrapping_concursos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CONCURSOS_CONFIG = {
    'ARQUIVO_BACKUP': 'concursos_backup.txt',
    'TOKEN_BOT': '7829942554:AAFuapRP-53eW0o54IOG7f3PavZr-jIH30U',
    'CHAT_ID': 2081844601,
    'ESTADOS_INTERESSE': ["AP", "PA", "GO", "MT", "MS", "PB", "MG", "SC", "RS", "PR", "NACIONAL"],
    'CARGOS_TI': [
        "tecnologia da informacao", "informatica", "analista de sistema", "analise de sistema", "analise em sistema",  
        "arquiteto de sistema", "arquitetura de sistema", "engenheiro de sistema", "engenharia de sistema", "especialista em sistema", "especialidade em sistema",  
        "gerente de sistema", "gerenciamento de sistema", "gestao de sistema", "coordenador de sistema", "coordenacao de sistema",  
        "tecnico de sistema", "tecnica de sistema", "consultor de sistema", "consultoria de sistema", "administrador de sistema", "administracao de sistema",  
        "suporte de sistema",  "testador de sistema", "testes de sistema", "testagem de sistema",  "sistemas",
        "auditor de sistema", "auditoria de sistema",  "operador de sistema", "operacao de sistema",  "cientista de sistema", "ciencia de sistema",  
        "líder de sistema", "liderança de sistema", "computacao", "desenvolvimento de", "analisa de desenvolvimento", 
        "tecnico em desenvolvimento", "especialista em desenvolvimento", "engenheiro de desenvolvimento", "desenvolvedor", "seguranca da informacao", "banco de dados", 
        "redes", "suporte tecnico", "programacao", "programador", "engenharia de software", "arquitetura de software", "infraestrutura de ti", 
        "suporte de ti", "analista de ti", "cientista de dados", "inteligencia artificial", "ciencia de dados", "aprendizado de maquina",
        "governanca de ti", "gestao de projetos de ti", "gestao de riscos de ti", "computacao em nuvem", "forense digital", "tecnologista", "tecnologic",
        "big data", "automacao", "devops", "analise de dados", "analista de dados", "ciencia e tecnologia"
    ],
    'TERMOS_EXCLUIR': [
        "informatica basica", "nocoes de informatica", "informatica para iniciantes", "conceitos de informatica", 
        "conhecimentos em informatica", "cursos de informatica", ", informatica", "informatica nivel basico", 
        "informatica nivel iniciante", "informatica fundamental", "nivel basico em informatica", "; informatica",
        "basico em informatica", "basico de informatica", "basicos em informatica", "basicos de informatica", 
        "iniciante em informatica", "iniciante de informatica"
    ],
    'URL_BASE_PCI': "https://www.pciconcursos.com.br/concursos/"
}