# Generated by Django 5.1.7 on 2025-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.URLField(unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('data_concurso', models.DateField()),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('novo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
