name: Scraper de Concursos TI

on:
  schedule:
    - cron: '0 21 * * *'  # Executa diariamente às 09:00 BRT (12:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da branch daily-scraper-job
      uses: actions/checkout@v4
      with:
        ref: daily-scraper-job
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      id: scraper
      run: python src/main.py
      env:
        TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
        CHAT_ID: ${{ secrets.CHAT_ID }}

    - name: Commit and push database changes
      if: steps.scraper.outcome == 'success'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git status
        git diff --exit-code concursos.db || CHANGES=true

        if [[ $CHANGES ]]; then
          git add concursos.db
          git commit -m "[Automated] Update database - $(date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin daily-scraper-job
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
          git push origin daily-scraper-job
          echo "Database updated successfully"
        else
          echo "No changes in database"
        fi
